CREATE TABLE CURRENCY_COURSE
(
    CURRENCY_COURSE_ID   SERIAL NOT NULL
        CONSTRAINT ROLES_PKEY
            PRIMARY KEY,
    CURRENCY_NAME VARCHAR NOT NULL,
    CURRENCY_PRICE FLOAT NOT NULL ,
    CURRENCY_PRICE_DATE_TIME TIMESTAMP DEFAULT NOW() NOT NULL
);
